apiVersion: paas.sogou.com/v1
kind: LogConfig
metadata:
  name: puppeteer-server-log
  namespace: search-databus
  labels:
    paas.sogou.com/app: puppeteer-server
spec:
  selector:
    paas.sogou.com/app: puppeteer-server
  mode: agent
  logs:
    - inputType: stdout
      containerName: puppeteer-server
      encoding: utf-8
      multiline:
        pattern: '\[.+] \[\w+]'
        negate: true
        match: after
        maxLines: 500
        timeout: "10s"
      paths:
        - "null"
      fields:
        kafkaTopic: default
        logType: info
      fieldsUnderRoot: true
      tailFiles: false
      closeRenamed: true
